FROM python:3

WORKDIR /usr/src/app

COPY ./pv_simulator/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./pv_simulator/src ./src
COPY ./shared ./shared
COPY ./pv_simulator/test ./test
CMD [ "python", "-m", "unittest"]